import base64
import binascii
import os
from collections.abc import Mapping
from typing import Any

from openai import (
    APIConnectionError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    InternalServerError,
    NotFoundError,
    OpenAI,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
)

from app.ai.image_enhancement import (
    OPENAI_IMAGE_PROVIDER,
    ImageEnhancementRequest,
    ImageEnhancementResult,
    PermanentImageEnhancementProviderError,
    RetryableImageEnhancementProviderError,
    normalize_image_enhancement_parameters,
)


class OpenAIImageEnhancementProvider:
    """OpenAI Images edit adapter returning transient generated bytes only."""

    name = OPENAI_IMAGE_PROVIDER

    def __init__(self, client: Any) -> None:
        self._client = client

    @classmethod
    def from_environment(cls) -> "OpenAIImageEnhancementProvider":
        api_key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not api_key:
            raise PermanentImageEnhancementProviderError(
                "OpenAI API credentials are not configured"
            )
        return cls(OpenAI(api_key=api_key, max_retries=0))

    def enhance(self, request: ImageEnhancementRequest) -> ImageEnhancementResult:
        parameters = normalize_image_enhancement_parameters(request.parameters)
        if not request.source.content:
            raise PermanentImageEnhancementProviderError("source image is empty")
        extension = {
            "image/jpeg": ".jpg",
            "image/png": ".png",
            "image/webp": ".webp",
        }.get(request.source.mime_type)
        if extension is None:
            raise PermanentImageEnhancementProviderError(
                "source image MIME type is unsupported"
            )
        options = {
            "model": request.model,
            "image": (
                f"source{extension}",
                request.source.content,
                request.source.mime_type,
            ),
            "prompt": request.prompt,
            "quality": parameters["quality"],
            "output_format": parameters["output_format"],
            "size": parameters["size"],
            "background": parameters["background"],
        }
        try:
            response = self._client.images.edit(**options)
        except Exception as error:
            raise _classify_openai_error(error) from None
        data = getattr(response, "data", None) or ()
        encoded = _get_value(data[0], "b64_json") if data else None
        if not encoded:
            raise RetryableImageEnhancementProviderError(
                "OpenAI image edit returned no output data"
            )
        try:
            output_bytes = base64.b64decode(encoded, validate=True)
        except (binascii.Error, ValueError, TypeError):
            raise PermanentImageEnhancementProviderError(
                "OpenAI image edit returned invalid output data"
            ) from None
        if not output_bytes:
            raise RetryableImageEnhancementProviderError(
                "OpenAI image edit returned no output data"
            )
        return ImageEnhancementResult(
            output_bytes=output_bytes,
            output_format_hint=_get_value(data[0], "output_format"),
            usage=_normalize_usage(response),
        )


def _classify_openai_error(error: Exception) -> Exception:
    if isinstance(
        error,
        (
            APITimeoutError,
            APIConnectionError,
            APIResponseValidationError,
            RateLimitError,
            InternalServerError,
        ),
    ):
        return RetryableImageEnhancementProviderError(
            "temporary OpenAI image enhancement failure"
        )
    if isinstance(
        error,
        (
            AuthenticationError,
            PermissionDeniedError,
            NotFoundError,
            BadRequestError,
            UnprocessableEntityError,
        ),
    ):
        return PermanentImageEnhancementProviderError(
            "OpenAI image enhancement request or access was rejected"
        )
    if isinstance(error, APIStatusError):
        if error.status_code in {408, 409, 429} or error.status_code >= 500:
            return RetryableImageEnhancementProviderError(
                "temporary OpenAI image enhancement failure"
            )
        return PermanentImageEnhancementProviderError(
            "OpenAI image enhancement request or access was rejected"
        )
    return PermanentImageEnhancementProviderError(
        "unexpected OpenAI image enhancement failure"
    )


def _normalize_usage(response: Any) -> dict[str, int | str]:
    usage = getattr(response, "usage", None)
    normalized: dict[str, int | str] = {}
    for name in ("input_tokens", "output_tokens", "total_tokens"):
        value = _get_value(usage, name)
        if value is not None:
            normalized[name] = value
    details = _get_value(usage, "input_tokens_details")
    for source_name, target_name in (
        ("image_tokens", "input_image_tokens"),
        ("text_tokens", "input_text_tokens"),
    ):
        value = _get_value(details, source_name)
        if value is not None:
            normalized[target_name] = value
    return normalized


def _get_value(source: Any, name: str) -> Any:
    if source is None:
        return None
    if isinstance(source, Mapping):
        return source.get(name)
    return getattr(source, name, None)
